@host = http://localhost:3000
@token = {{obtainToken.response.body.$.token}}

# @name obtainToken
POST {{host}}/api/login
Content-Type: application/json

{
    "email": "krolik",
    "password": "asd"
}

###
GET {{host}}

###
POST {{host}}/shfunc
Content-Type: application/json
Authorization: {{token}}